hpc_determining_command: squeue # If this command is found, treat machine as HPC
hpc_submit_command: sbatch

# Determine job run time and resources
hpcs:
  getafix:
    account: smp
    conda_env: Barry
    job_script_name: getafix
    num_fits_per_job: 1
    mpi_module: openmpi3_eth/3.0.0
    fort_compile_module: gnu/7.2.0
    num_concurrent: 200

  cori:
    account: desi
    job_script_name: cori
    num_fits_per_job: 32
    mpi_module: cray-mpich/7.7.19
    fort_compile_module: gcc

  perlmutter:
    account: desi
    job_script_name: perlmutter
    num_fits_per_job: 32
    mpi_module: cray-mpich/7.7.19
    fort_compile_module: gcc